# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build nextjs-eg-app`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t nextjs-eg-app`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system nextjs-eg-app && \
          adduser --system -G nextjs-eg-app nextjs-eg-app

COPY dist/nextjs-eg-app nextjs-eg-app/
RUN chown -R nextjs-eg-app:nextjs-eg-app .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix nextjs-eg-app --omit=dev -f install

CMD [ "node", "nextjs-eg-app" ]
